triggers:
  pull-requests:
    event: PR

workflows:
  main:
    runs-on: linux-medium-js
    distribute: true
    steps:
      - name: Affected build
        script: npx nx affected -t build test
  checks:
    runs-on: linux-medium-js
    steps:
      - name: Show projects
        script: npx nx show projects
